openapi: 3.0.1
info:
  title: WPEX - Covid Pathology Test Results
  description: ""
  version: "1.0"
servers:
  - url: "https://dhew-fhir-r4.azurewebsites.net/fhir"
paths:
  /$process-message:
    post:
      summary: Process-Message
      description: "This is a FHIR endpoint that accepts a FHIR Message bundle. The bundle or type Message must have a MessageHeader resource as the first resouce in the bundle and should conform to the [official FHIR documentation](https://www.hl7.org/fhir/messageheader-operation-process-message.html) .\n\nThe bundle should contain at least one of each of the following FHIR Resources : \n\n* [Bundle](https://www.hl7.org/fhir/bundle.html) \n\n* [MessageHeader](https://www.hl7.org/fhir/messageheader.html) \n\n* [Organization](https://www.hl7.org/fhir/organization.html) \n\n* [DiagnosticReport](https://www.hl7.org/fhir/diagnosticreport.html) \n\n* [Patient](https://www.hl7.org/fhir/patient.html) \n\n* [Encounter](https://www.hl7.org/fhir/encounter.html) \n\n* [Observation] (1 or more)[https://www.hl7.org/fhir/observation.html] \n\n* [ServiceRequest](https://www.hl7.org/fhir/servicerequest.html) \n\n* [Specimen](https://www.hl7.org/fhir/specimen.html) \n\n* [Device](https://www.hl7.org/fhir/device.html) \n\n* [Media](https://www.hl7.org/fhir/media.html). \n\nYou may want to view the sample FHIR structure in the 'try it' button on the developer portal. \n\nExamples are available in a Postman collection:\n\n[![Run in Postman] (TODO Add the Postman Link to complete this ...)"
      operationId: post-process-message
      responses:
        "200":
          description: Success
