openapi: 3.0.1
info:
  title: WRRS - FHIR Diagnostics
  version: '1.0'
paths:
  /DiagnosticReport:
    get:
      summary: DiagnosticReport
      description: "A single DiagnosticReport will contain the results of tests ordered during a single encounter. Note that a single order may have requested multiple tests across multiple specimens.\n\nSome *test profiles* in the Welsh Pathology Handbook include multiple tests.  For example the Urea and Electrolytes profile contains tests for Sodium Potassium, Urea and Creatinine.  In these cases the DiagnosticReport will contain an Observation for the test profile which then references the individual test results via it's [Observation.related](http://hl7.org/fhir/STU3/observation.html) property with a type of \"has-member\".\n\n\n##### Example Usage: Retrieve a patient’s test results \n\nTo retrieve a list of orders and corresponding results, use the Patient.id for the patient in question and pass it as the value for  patient search parameter, e.g.\n\n`GET {baseUrl}/DiagnosticReport?patient=43`\n\nIdeally, you would also be able to filter by the encounter search parameter and supply the id of the encounter when the order was made.  We currently do not have an API for retrieving Encounter resources."
      operationId: get-diagnosticreport
      parameters:
        - name: _language
          in: query
          description: The language of the resource
          schema:
            type: string
        - name: encounter
          in: query
          description: The Encounter when the order was made
          schema:
            type: string
        - name: result
          in: query
          description: Link to an atomic result (observation resource)
          schema:
            type: string
        - name: patient
          in: query
          description: The subject of the report if a patient
          schema:
            type: string
        - name: _format
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
  '/DiagnosticReport/{id}':
    get:
      summary: 'DiagnosticReport/{id}'
      operationId: get-diagnosticreport-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /Observation:
    get:
      summary: Observation
      description: "Each Observation resource represents the result of a test on a specimen.\n\n##### Example Usage: Retrieve a series of a single test type\n\nIf a patient has several results for the same test type, e.g. regular HbA1c tests for a patient with diabetes, you may want to retrieve all the results to display them in a table or plot them on a chart.\n\nAs an example, to retrieve all of a patient's sodium results (code NA), use the Patient.id for the patient in questions and pass it as the value of the patient search parameter, and supply the code for the test type as the code search parameter\n\n`GET {baseUrl}/Observation?patient=43&code=NA`"
      operationId: get-observation
      parameters:
        - name: _language
          in: query
          description: The language of the resource
          schema:
            type: string
        - name: date
          in: query
          description: 'Format - date (as full-date in RFC3339). Obtained date/time. If the obtained element is a period, a date that falls in the period'
          schema:
            type: string
        - name: code
          in: query
          description: The code of the observation type
          schema:
            type: string
        - name: patient
          in: query
          description: The subject that the observation is about (if patient)
          schema:
            type: string
        - name: specimen
          in: query
          description: Specimen used for this observation
          schema:
            type: string
        - name: encounter
          in: query
          description: Encounter related to the observation
          schema:
            type: string
        - name: _format
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
  '/Observation/{id}':
    get:
      summary: 'Observation/{id}'
      operationId: get-observation-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
components:
  schemas:
    DiagnosticReport:
      required:
        - resourceType
        - id
        - text
        - contained
        - identifier
        - status
        - category
        - code
        - subject
        - encounter
        - effectiveDateTime
        - issued
        - _issued
        - performer
        - result
        - presentedForm
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        text:
          required:
            - status
            - div
          type: object
          properties:
            status:
              minLength: 1
              type: string
            div:
              minLength: 1
              type: string
        contained:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
              - resourceType
              - id
              - status
            properties:
              resourceType:
                minLength: 1
                type: string
              id:
                minLength: 1
                type: string
              _id:
                required:
                  - fhir_comments
                type: object
                properties:
                  fhir_comments:
                    type: array
                    items: { }
              status:
                minLength: 1
                type: string
              code:
                required:
                  - coding
                  - text
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                        - system
                        - code
                        - display
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
                        display:
                          minLength: 1
                          type: string
                  text:
                    minLength: 1
                    type: string
              subject:
                required:
                  - reference
                type: object
                properties:
                  reference:
                    minLength: 1
                    type: string
              performer:
                minItems: 1
                uniqueItems: true
                type: array
                items:
                  required:
                    - reference
                    - display
                  properties:
                    reference:
                      minLength: 1
                      type: string
                    display:
                      minLength: 1
                      type: string
              valueQuantity:
                required:
                  - value
                  - unit
                  - system
                  - code
                type: object
                properties:
                  value:
                    type: number
                  unit:
                    minLength: 1
                    type: string
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
              referenceRange:
                minItems: 1
                uniqueItems: true
                type: array
                items:
                  properties:
                    low:
                      required:
                        - value
                        - unit
                        - system
                        - code
                      type: object
                      properties:
                        value:
                          type: number
                        unit:
                          minLength: 1
                          type: string
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
                    high:
                      required:
                        - value
                        - unit
                        - system
                        - code
                      type: object
                      properties:
                        value:
                          type: number
                        unit:
                          minLength: 1
                          type: string
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
        identifier:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
              - system
              - value
            properties:
              system:
                minLength: 1
                type: string
              value:
                minLength: 1
                type: string
        status:
          minLength: 1
          type: string
        category:
          required:
            - coding
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                  - system
                  - code
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
        code:
          required:
            - fhir_comments
            - coding
            - text
          type: object
          properties:
            fhir_comments:
              type: array
              items: { }
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                  - system
                  - code
                  - display
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
                  display:
                    minLength: 1
                    type: string
            text:
              minLength: 1
              type: string
        subject:
          required:
            - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        encounter:
          required:
            - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        effectiveDateTime:
          minLength: 1
          type: string
        issued:
          minLength: 1
          type: string
        _issued:
          required:
            - fhir_comments
          type: object
          properties:
            fhir_comments:
              type: array
              items: { }
        performer:
          required:
            - reference
            - display
          type: object
          properties:
            reference:
              minLength: 1
              type: string
            display:
              minLength: 1
              type: string
        result:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
              - reference
            properties:
              fhir_comments:
                type: array
                items: { }
              reference:
                minLength: 1
                type: string
        presentedForm:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
              - contentType
              - language
              - data
              - title
            properties:
              fhir_comments:
                type: array
                items: { }
              contentType:
                minLength: 1
                type: string
              language:
                minLength: 1
                type: string
              data:
                minLength: 1
                type: string
              title:
                minLength: 1
                type: string
      description: ''
    Observation:
      required:
        - resourceType
        - id
        - text
        - status
        - category
        - code
        - subject
        - encounter
        - effectiveDateTime
        - valueQuantity
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        text:
          required:
            - fhir_comments
            - status
            - div
          type: object
          properties:
            fhir_comments:
              type: array
              items: { }
            status:
              minLength: 1
              type: string
            div:
              minLength: 1
              type: string
        status:
          minLength: 1
          type: string
        category:
          required:
            - fhir_comments
            - coding
          type: object
          properties:
            fhir_comments:
              type: array
              items: { }
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                  - system
                  - code
                  - display
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
                  display:
                    minLength: 1
                    type: string
        code:
          required:
            - fhir_comments
            - coding
          type: object
          properties:
            fhir_comments:
              type: array
              items: { }
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                  - system
                  - code
                  - display
                properties:
                  fhir_comments:
                    type: array
                    items: { }
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
                  display:
                    minLength: 1
                    type: string
                  _display:
                    required:
                      - fhir_comments
                    type: object
                    properties:
                      fhir_comments:
                        type: array
                        items: { }
        subject:
          required:
            - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        encounter:
          required:
            - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        effectiveDateTime:
          minLength: 1
          type: string
        valueQuantity:
          required:
            - fhir_comments
            - value
            - unit
            - system
            - code
          type: object
          properties:
            fhir_comments:
              type: array
              items: { }
            value:
              type: number
            unit:
              minLength: 1
              type: string
            system:
              minLength: 1
              type: string
            code:
              minLength: 1
              type: string
      description: ''