openapi: 3.0.1
info:
  title: WRDS - Reference Data & Schema Lookup
  version: '1.0'
paths:
  '/GetTable/{namespace}/{tablename}':
    get:
      tags:
        - NRDS
      summary: GetTable
      description: Retrieve the XML for a given reference table.
      operationId: GetTable
      parameters:
        - name: namespace
          in: path
          description: The namespace the table belongs to
          required: true
          schema:
            enum:
              - nrds
              - gp2gp
            type: string
            default: nrds
        - name: tablename
          in: path
          description: The table/view you want to retrieve data from
          required: true
          schema:
            enum:
              - GPPracticeMembership
              - WelshOrganisation
              - vwClinicianMaster
              - SexualHealthClinicsWales
              - AssigningAuthority
              - WelshGPPracticeMainSites
            type: string
            default: WelshOrganisation
        - name: nrd:org_code
          in: query
          schema:
            enum:
              - '49998'
            type: 'string'
            default: ''
      responses:
        '200':
          description: OK
          content:
            application/xml: { }
  '/GetTableSchema/{namespace}/{tablename}':
    get:
      tags:
        - NRDS
      summary: GetTableSchema
      description: Retrieve the XML Schema for a given reference table.
      operationId: GetTableSchema
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            enum:
              - nrds
              - gp2gp
            type: string
            default: nrds
        - name: tablename
          in: path
          required: true
          schema:
            enum:
              - GPPracticeMembership
              - WelshOrganisation
              - vwClinicianMaster
              - SexualHealthClinicsWales
              - AssigningAuthority
              - WelshGPPracticeMainSites
            type: string
            default: WelshOrganisation
      responses:
        '200':
          description: OK
          content:
            application/xml: { }
  '/GetNamespaceSchema/{namespace}':
    get:
      tags:
        - NRDS
      summary: GetNamespaceSchema
      description: Retrieve the XML Schema for all elements (i.e. NRDS atrributes) in a given namespace.
      operationId: GetNamespaceSchema
      parameters:
        - name: namespace
          in: path
          description: The namespace you want to explore
          required: true
          schema:
            enum:
              - nrds
              - gp2gp
            type: string
            default: nrds
      responses:
        '200':
          description: OK
          content:
            application/xml: { }
